version: '3'

services:
  db:
    image: bitnami/postgresql
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=pairtner
      - POSTGRESQL_PASSWORD=pairtner
      - POSTGRESQL_DATABASE=pairtner-db
volumes:
  postgres_data: